#include "data/DatabaseWorker.h"
#include <exchange_state/OrderIDGenerator.h>
#include <gtest/gtest.h>
#include <memory>
#include <set>
#include <thread>
#include <vector>

// Test fixture for OrderIDGenerator tests.
class OrderIDGeneratorTest : public ::testing::Test {
protected:
    void SetUp() override
    {
        // In a real test environment, we might use a mock or a test database.
        // For this unit test, we assume the database is not reachable,
        // so the generator will start from the default ID (0).
        dbWorker = std::make_unique<data::DatabaseWorker>(""); // Empty path
        generator = std::make_unique<trading_core::OrderIDGenerator>(
                dbWorker.get());
    }

    std::unique_ptr<data::DatabaseWorker> dbWorker;
    std::unique_ptr<trading_core::OrderIDGenerator> generator;
};

TEST_F(OrderIDGeneratorTest, SequentialIDGeneration)
{
    // The generator should start from 0 and increment.
    EXPECT_EQ(generator->nextId(), 1);
    EXPECT_EQ(generator->nextId(), 2);
    EXPECT_EQ(generator->nextId(), 3);
}

TEST_F(OrderIDGeneratorTest, ThreadSafety)
{
    const int num_threads = 10;
    const int ids_per_thread = 1000;
    const int total_ids = num_threads * ids_per_thread;

    std::vector<std::thread> threads;
    std::vector<common::OrderID> generated_ids(total_ids);

    auto generate_ids_task = [&](int start_index) {
        for (int i = 0; i < ids_per_thread; ++i) {
            generated_ids[start_index + i] = generator->nextId();
        }
    };

    for (int i = 0; i < num_threads; ++i) {
        threads.emplace_back(generate_ids_task, i * ids_per_thread);
    }

    for (auto& t: threads) { t.join(); }

    // Check for uniqueness.
    std::sort(generated_ids.begin(), generated_ids.end());
    auto it = std::unique(generated_ids.begin(), generated_ids.end());
    bool is_unique = (it == generated_ids.end());

    ASSERT_TRUE(is_unique)
            << "Duplicate OrderIDs were generated by concurrent threads.";

    // Check if the final ID is close to the total number of IDs generated.
    // The next ID should be total_ids + 1.
    EXPECT_EQ(generator->nextId(), total_ids + 1);
}
