#include <gtest/gtest.h>
#include "trading_core/OrderIDGenerator.h"
#include <vector>
#include <thread>
#include <algorithm>
#include <set>

// Test fixture for OrderIDGenerator tests to ensure state is reset.
class OrderIDGeneratorTest : public ::testing::Test {
protected:
    void SetUp() override {
        // Reset the state before each test to ensure test independence.
        trading_core::OrderIDGenerator::loadState();
    }
};

TEST_F(OrderIDGeneratorTest, SequentialIDGeneration) {
    ASSERT_EQ(trading_core::OrderIDGenerator::getId(), 0);
    EXPECT_EQ(trading_core::OrderIDGenerator::nextId(), 1);
    EXPECT_EQ(trading_core::OrderIDGenerator::nextId(), 2);
    EXPECT_EQ(trading_core::OrderIDGenerator::getId(), 2);
    EXPECT_EQ(trading_core::OrderIDGenerator::nextId(), 3);
    EXPECT_EQ(trading_core::OrderIDGenerator::getId(), 3);
}

TEST_F(OrderIDGeneratorTest, StateReset) {
    // Generate some IDs
    trading_core::OrderIDGenerator::nextId();
    trading_core::OrderIDGenerator::nextId();
    ASSERT_EQ(trading_core::OrderIDGenerator::getId(), 2);

    // Reset the state
    trading_core::OrderIDGenerator::loadState();

    // Verify the state is reset
    ASSERT_EQ(trading_core::OrderIDGenerator::getId(), 0);
    EXPECT_EQ(trading_core::OrderIDGenerator::nextId(), 1);
}

TEST_F(OrderIDGeneratorTest, ThreadSafety) {
    const int num_threads = 10;
    const int ids_per_thread = 1000;
    const int total_ids = num_threads * ids_per_thread;

    std::vector<std::thread> threads;
    std::vector<common::OrderID> generated_ids;
    generated_ids.resize(total_ids);
    std::mutex vector_mutex; // To protect access to the shared vector

    auto generate_ids_task = [&](int start_index) {
        for (int i = 0; i < ids_per_thread; ++i) {
            generated_ids[start_index + i] = trading_core::OrderIDGenerator::nextId();
        }
    };

    for (int i = 0; i < num_threads; ++i) {
        threads.emplace_back(generate_ids_task, i * ids_per_thread);
    }

    for (auto& t : threads) {
        t.join();
    }

    // 1. Check if the total number of IDs is correct.
    // This also checks that no thread overwrote another's result in the vector.
    ASSERT_EQ(generated_ids.size(), total_ids);

    // 2. Check for uniqueness.
    std::sort(generated_ids.begin(), generated_ids.end());
    auto it = std::unique(generated_ids.begin(), generated_ids.end());
    bool is_unique = (it == generated_ids.end());
    
    ASSERT_TRUE(is_unique) << "Duplicate OrderIDs were generated by concurrent threads.";

    // 3. Check if the final ID matches the total number of IDs generated.
    EXPECT_EQ(trading_core::OrderIDGenerator::getId(), total_ids);
}
