#include "data/DatabaseWorker.h"
#include "data/TradeIDRepository.h"
#include "trading_core/TradeIDGenerator.h"
#include <chrono>
#include <future>
#include <gtest/gtest.h>
#include <memory>
#include <set>
#include <thread>
#include <vector>

class TradeIDGeneratorTest : public ::testing::Test {
protected:
    std::unique_ptr<data::DatabaseWorker> dbWorker;
    std::unique_ptr<data::TradeIDRepository> tradeIDRepo;
    std::unique_ptr<trading_core::TradeIDGenerator> generator;

    void SetUp() override
    {
        // Use an in-memory database for tests
        dbWorker = std::make_unique<data::DatabaseWorker>(":memory:");
        tradeIDRepo = std::make_unique<data::TradeIDRepository>(dbWorker.get());
        // Ensure the database table is created and the ID is reset before each
        // test
        tradeIDRepo->truncateTradeID();
        dbWorker->waitUntilIdle(); // Wait for truncate to finish

        // Initialize the generator after the database is set up
        generator = std::make_unique<trading_core::TradeIDGenerator>(
                tradeIDRepo.get());
    }

    void TearDown() override
    {
        generator.reset(); // Destroy generator first so it can schedule saveState()
        if (dbWorker) {
            dbWorker->waitUntilIdle(); // Wait for all pending tasks to complete
            dbWorker.reset(); // Now it's safe to destroy the worker
        }
    }
};

TEST_F(TradeIDGeneratorTest, InitialStateLoading)
{
    // 1. Manually set a starting ID in the database
    const common::TradeID start_id = 100;
    tradeIDRepo->setCurrentTradeID(start_id);
    dbWorker->waitUntilIdle(); // Wait for the write to complete

    // Re-initialize the generator to load the new state
    generator
            = std::make_unique<trading_core::TradeIDGenerator>(tradeIDRepo.get());

    // The generator should have loaded the state, so the first generated ID
    // should be start_id + 1.
    EXPECT_EQ(generator->nextId(), start_id + 1);
}

TEST_F(TradeIDGeneratorTest, SequentialGenerationAfterLoading)
{
    const common::TradeID start_id = 50;
    tradeIDRepo->setCurrentTradeID(start_id);
    dbWorker->waitUntilIdle(); // Wait for write to complete

    // Re-initialize the generator to load the new state
    generator
            = std::make_unique<trading_core::TradeIDGenerator>(tradeIDRepo.get());

    // Verify sequential generation
    EXPECT_EQ(generator->nextId(), start_id + 1);
    EXPECT_EQ(generator->nextId(), start_id + 2);
    EXPECT_EQ(generator->nextId(), start_id + 3);
}

TEST_F(TradeIDGeneratorTest, StatePersistenceOnDestruction)
{
    const common::TradeID final_id = 5;

    // Re-initialize the generator to ensure it starts from a known state (0
    // in this case)
    generator = std::make_unique<trading_core::TradeIDGenerator>(
            tradeIDRepo.get());

    for (common::TradeID i = 0; i < final_id; ++i) { generator->nextId(); }
    // The generator's destructor will be called here, triggering
    // saveState()
    generator.reset(); // explicitly destroy generator

    // The save is async, so we must wait for it to land in the database.
    dbWorker->waitUntilIdle();

    // Verify the saved state by using the repository directly
    std::promise<common::TradeID> read_promise;
    std::future<common::TradeID> read_future = read_promise.get_future();
    tradeIDRepo->getCurrentTradeID(
            [&](common::TradeID id) { read_promise.set_value(id); });

    // We must still wait for the read operation itself to complete
    dbWorker->waitUntilIdle();

    // The saved ID should be the last generated ID, which is 'final_id'.
    EXPECT_EQ(read_future.get(), final_id);
}

TEST_F(TradeIDGeneratorTest, ThreadSafety)
{
    const int num_threads = 10;
    const int ids_per_thread = 1000;
    const int total_ids = num_threads * ids_per_thread;

    std::vector<std::thread> threads;
    std::vector<common::TradeID> generated_ids(total_ids);

    auto generate_ids_task = [&](int start_index) {
        for (int i = 0; i < ids_per_thread; ++i) {
            generated_ids[start_index + i] = generator->nextId();
        }
    };

    for (int i = 0; i < num_threads; ++i) {
        threads.emplace_back(generate_ids_task, i * ids_per_thread);
    }

    for (auto& t: threads) { t.join(); }

    // Check for uniqueness.
    std::sort(generated_ids.begin(), generated_ids.end());
    auto it = std::unique(generated_ids.begin(), generated_ids.end());
    bool is_unique = (it == generated_ids.end());

    ASSERT_TRUE(is_unique)
            << "Duplicate TradeIDs were generated by concurrent threads.";

    // The last generated ID should be total_ids (assuming it started from 0 or
    // loaded state was 0). If it started from 0, the last generated ID would be
    // total_ids. If it loaded a state, say `S`, then the last generated ID
    // would be `S + total_ids`. Since we truncate the ID in SetUp, it should
    // start from 0. So, the next ID after all generations should be total_ids
    // + 1.
    EXPECT_EQ(generator->nextId(), total_ids + 1);
}
